import type { NextPage } from "next";
import Head from "next/head";
import SectionLayout from '../components/index/SectionLayout';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Gate Game 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full min-h-screen">
        <SectionLayout bgColor='bg-black'>
          <h1>
            <span className='text-gate-and-primary'>
              I
            </span>
            <span className='text-gate-or-primary'>
              T
            </span>
            <span className='text-gate-not-primary'>
              G
            </span>
            <span className='text-gate-nor-primary'>
              G
            </span>
            <span className='text-gate-and-orange'>
              2022
            </span>
          </h1>
        </SectionLayout>

        <SectionLayout bgColor='bg-white'>
          <h2>ตารางคะแนน</h2>
          <h6>อัพเดทล่าสุดเมื่อ 07/09/2022 15.39 น.</h6>
        </SectionLayout>
      </main>
    </>
  );
};

export default Home;
