import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="w-screen h-screen flex flex-col items-center">
      <Head>
        <title>Gate Game 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full min-h-screen grid place-items-center">
        <h1 className="text-5xl font-semibold">Coming Soon</h1>
      </main>
    </div>
  );
};

export default Home;
